publish:
  docker:
    registry: $$DOCKER_REGISTRY
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: $${DOCKER_REGISTRY}/$${DOCKER_USERNAME}/nsp-web
    tag: "$$BUILD_NUMBER"
    when:
      event: push
      branch: master
notify:
  slack:
    webhook_url: $$SLACK_HOOK
    channel: alerts
    username: drone
