publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: andyet/nsp-web
    tag: "$$BUILD_NUMBER"
    when:
      event: deployment
notify:
  slack:
    webhook_url: $$SLACK_HOOK
    channel: alerts
    username: drone
